#-------------------------------
# General Site Settings

title: Dr. Pearl Pugh
description: God // Family // Entrepreneur // Author
email: Pugh.pearl@yahoo.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Works, url: '#work'}
- {name: Contact, url: '#contact'}
- {name: Meet Pearl, url: 'meet-me.html'}
- {name: Product Order, url: 'product-order.html'}
- {name: Mini Subscribe, url: 'mini-subscribe.html'}
- {name: Booking, url: 'booking-form.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: ''
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
 **A pioneering visionary, compelling speaker, trailblazing author, and serial entrepreneur** Pearl is taking the world by storm with her determination 
 and desire for seeing transformation in every aspect of her life. Hailing proudly from the windy city of Chicago, IL, Pearl took note of her passion, 
 dreams, and clear vision for the future at a very young age.

#-------------------------------
# Work Section

projects:
- {name: Wife/Mom, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Business Owner, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Author, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Educator, folder: 'proj-4', file: 'work/proj-4.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'facebook', link: 'https://www.facebook.com/pearl.clark.9'}
- {icon: 'instagram', link: 'https://www.instagram.com/pugh.pearl/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/pearl-clark-90080932?trk=people-guest_people_search-card'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
